language: "node_js"
node_js:
  - "8"
  - "6"
  - "4"


before_install:
  - "npm install make-node@0.3.x -g"
  - "preinstall-compat"

script:
  - "make test-cov"

after_success:
  - "make report-cov"

sudo: false
